#ifndef GAME_STATE_ENUM_H
#define GAME_STATE_ENUM_H

enum game_state {MAIN_MENU,SERVER_OR_CLIENT_SELECT_MENU,COOP_MODE_SELECT_MENU,PLAYING,PAUSE_MENU,DIE_SCREEN,DIFFICULTY_SELECT,SERVER_START_SCREEN};

#endif // GAME_STATE_ENUM_H
